# Generated by Django 6.0.5 on 2026-08-05 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog_redesign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogview',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameIndex(
            model_name='blog',
            new_name='core_blog_status_3a6c8d_idx',
            old_name='core_blog_status_pub_3b0f21_idx',
        ),
        migrations.RenameIndex(
            model_name='blog',
            new_name='core_blog_author__79f96a_idx',
            old_name='core_blog_author__d5f614_idx',
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Featured / hero cover image.', null=True, upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary shown on cards.', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the post goes (or went) live. Leave blank to publish now.', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
